### ISSUE TITLE
Media File Download error

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#482]
When clicking on any download link:

1054 Unknown column 's6hej_bsms_servers.server_path' in 'field list' SQL=SELECT s6hej_bsms_mediafiles.*, s6hej_bsms_servers.id AS ssid, s6hej_bsms_servers.server_path AS spath FROM s6hej_bsms_mediafiles LEFT JOIN s6hej_bsms_servers ON (s6hej_bsms_servers.id = s6hej_bsms_mediafiles.server) WHERE s6hej_bsms_mediafiles.id = 2900 LIMIT 0, 1

**Comment by bcordis** [comment]
@tomfuller2 Fixed in c2d02ca3a923e2a34946f53932562d23741a30de

**Comment by tomfuller2** [comment]
I'm not getting any downloads from upstream/development.

**Comment by bcordis** [comment]
Ok I'll look deeper as I see you updated the code thought you had fixed it. I'll work on it some more.

**Comment by tomfuller2** [comment]
No, it doesn't fix it - just tries to download a 0 byte file

**Comment by bcordis** [comment]
@tonfuller2 I'll debug it ASAP.

**Comment by tomfuller2** [comment]
Thanks!

**Comment by bcordis** [comment]
@tomfuller2 This should work now. Lots of changes please test. I have tested locally and work right.

**Comment by tomfuller2** [comment]
Fixed https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/82ce941f2e412f31d82c884db6b9c3b8daf22a7c
