### ISSUE TITLE
Admin set defaults: Creating thumbnails hangs up

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#589]
I changed the system default setting for study in the admin view. This leads to a popup message: `You modified the default thumbnail size(s). Thumbnails will be recreated for: teachers,series,studies. Click OK to continue` (even if I did not change the sizes). Clicking OK, the 'creating thumsnails' hangs up and works (?) endless:
![creating_thumbnails](https://cloud.githubusercontent.com/assets/2517417/8397045/120819e6-1dbe-11e5-9ad3-86aa0d08c134.png)
 
What thumbnails are (re-)generated here? I don't have images after a fresh installation.

**Comment by st-anton** [comment]
This happens every time, when I press the 'save' button in the administration view, regardless what I did. Subsequently, no change is stored.

**Comment by genu** [comment]
@st-anton So what happens, is that dialog should only show up if the thumbnail sizes were changed.
![image](https://cloud.githubusercontent.com/assets/928780/8409648/4530c104-1e47-11e5-8904-a981e1cb3f6f.png)

If they were changed, then it will go back to all the thumbnail that exist, and resize them. That is the idea here.

Once the thumbnails are resized, then it saves the settings.

Something is happening during this process it seems. For example, you shouldn't see that dialog if you didn't change the thumbnail settings.

-Eugen

**Comment by genu** [comment]
Maybe fixed in last commit, need to validate.

**Comment by st-anton** [comment]
Now the 'Creating Thumbnails' is only invoked when an image size was changed. Works fine.

But stll, the creating itself runs endlessly. Maybe it is caused by lack of images. Example: I changed the teachers image size, but I do not have any teacher image in my system.

**Comment by bcordis** [comment]
That may need to have some more checks to see if image exists before trying to Chang them. @eugen needs to double check this.

**Comment by st-anton** [comment]
I added an image to one teacher, then changed the teacher thumbnail size. Still the same behaviour.
Where should the thumbnails be located? Are they generated first time, when adding them to the tacher, series, study?

**Comment by bcordis** [comment]
I can confirm this is not working. Need more help on this on @genu

**Comment by bcordis** [comment]
@tomfuller2 This should be working now. Need more testing.

**Comment by tomfuller2** [comment]
I set a default image for all the views with no errors.

**Comment by bcordis** [comment]
Closing.
